#!/bin/sh
# This file is part of md-declustered-tests and licensed under the GNU GPL v2

run_test() {
    TESTCASE="$1"

    . "$TESTCASE"

    if [ -z "$DESCRIPTION" ]; then
	echo "Please define a description for testcase $TESTCASE"
	return
    fi

    echo -n "$DESCRIPTION ..."
    if declare -fF do_test > /dev/null; then
	if declare -fF setup > /dev/null && ! setup; then
	    echo "SKIP"
	    return 0
	fi

	do_test
	RESULT=$?
	if [ $RESULT -eq 0 ]; then
	    echo "PASS"
	else
	    echo "FAIL"
	fi

	if declare -fF teardown > /dev/null && ! teardown; then
	    return 0
	fi
    else
	echo "No do_test() defined?"
    fi
}

if [ "$#" -eq 1 ]; then
    if [ -f $1 ]; then
	run_test $1
    fi
else
    for tc in tests/*; do
	run_test $tc
    done
fi
