#!/bin/sh
# This file is part of md-declustered-tests and licensed under the GNU GPL v2

DESCRIPTION="Hot add spare disk into array"

setup()
{
	modprobe md-declustered
	modprobe zram num_devices="5"

	for i in 0 1 2 3 4; do
		echo 1g > /sys/block/zram$i/disksize
	done

	mdadm --create /dev/md0 --level=declustered --raid-disks=4 /dev/zram0 \
		/dev/zram1 /dev/zram2 /dev/zram3 || return 1
}

do_test()
{
	cat /proc/mdstat | grep -q -e "Personalities: \[declustered\]" -a \
		-e "\[4/4\]\[UUUU\]" || return 1

	mdadm --add /dev/md0 /dev/zram4 || return 1

	cat /proc/mdstat | grep -q -e "zram4\[4\](S)" || return 1
}

teardown()
{
	mdadm --stop /dev/md0
	for i in 0 1 2 3 4; do
		mdadm --zero-superblock /dev/zram$i
	done
	modprobe -r md-declustered
	modprobe -r zram
}
